//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.StudentToActivities = new HashSet<StudentToActivity>();
        }
    
        public double Age { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string ClassNum { get; set; }
        public bool Sister { get; set; }
        public string Pharm { get; set; }
        public string Id { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual ICollection<StudentToActivity> StudentToActivities { get; set; }
    }
}
