//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public Teacher()
        {
            this.TeachersToActivities = new HashSet<TeachersToActivity>();
        }
    
        public bool Educator { get; set; }
        public string Id { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual ICollection<TeachersToActivity> TeachersToActivities { get; set; }
    }
}
