//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        public int TripId { get; set; }
        public string Guide { get; set; }
        public double DurationOfTheTrip { get; set; }
        public string Sites { get; set; }
        public string Buses { get; set; }
        public int Year { get; set; }
    
        public virtual Activity Activity { get; set; }
    }
}
